[package]
authors = ["equilibrium"]
description = "Substrate-based runtime version of Curve automated market maker."
edition = "2018"
name = "equilibrium-curve-amm"
version = "0.1.1"
license = "Apache-2.0"
repository = "https://github.com/equilibrium-eosdt/equilibrium-curve-amm"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

[dependencies.frame-support]
default-features = false
version = "3.0.0"
git = 'https://github.com/equilibrium-eosdt/substrate.git'
branch = "v3.0.0eq"

[dependencies.frame-system]
default-features = false
version = "3.0.0"
git = 'https://github.com/equilibrium-eosdt/substrate.git'
branch = "v3.0.0eq"

[dev-dependencies]
serde = { version = "1.0.101" }

[dev-dependencies.sp-core]
default-features = false
version = "3.0.0"
git = 'https://github.com/equilibrium-eosdt/substrate.git'
branch = "v3.0.0eq"

[dev-dependencies.sp-io]
default-features = false
version = "3.0.0"
git = 'https://github.com/equilibrium-eosdt/substrate.git'
branch = "v3.0.0eq"

[dependencies.sp-std]
default-features = false
version = "3.0.0"
git = 'https://github.com/equilibrium-eosdt/substrate.git'
branch = "v3.0.0eq"

[dependencies.sp-runtime]
default-features = false
version = "3.0.0"
git = 'https://github.com/equilibrium-eosdt/substrate.git'
branch = "v3.0.0eq"

[dev-dependencies.pallet-balances]
default-features = false
version = "3.0.0"
git = 'https://github.com/equilibrium-eosdt/substrate.git'
branch = "v3.0.0eq"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
    "sp-std/std",
	"sp-runtime/std",
]
