[package]
name = "node"
version = "0.1.0"
authors = ["equilibrium"]
description = "Example node to run equilibrium-curve-amm pallet"
edition = "2018"
license = "Apache-2.0"
build = "build.rs"
repository = "https://github.com/equilibrium-eosdt/equilibrium-curve-amm"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node"

[dependencies]
structopt = "0.3.8"

sc-cli = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq", features = ["wasmtime"] }
sp-core = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-executor = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq", features = ["wasmtime"] }
sc-service = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq", features = ["wasmtime"] }
sc-telemetry = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-keystore = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-inherents = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-transaction-pool = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-transaction-pool = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-consensus-aura = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-consensus-aura = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-consensus = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-consensus = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-finality-grandpa = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-finality-grandpa = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-client-api = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-runtime = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-api = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-rpc-api = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-blockchain = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sp-block-builder = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
sc-basic-authorship = { version = "0.9.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
substrate-frame-rpc-system = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
pallet-transaction-payment-rpc = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }
frame-benchmarking-cli = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }

node-runtime = { version = "0.1.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = 'https://github.com/equilibrium-eosdt/substrate.git', branch = "v3.0.0eq" }

[features]
default = []
runtime-benchmarks = [
	"node-runtime/runtime-benchmarks",
]
